export const countryCodes: Record<string, string> = {
  "Algieria": "dz",
  "Anglia": "gb-eng",
  "Arabia Saudyjska": "sa",
  "Argentyna": "ar",
  "Australia": "au",
  "Austria": "at",
  "Belgia": "be",
  "Bośnia i Hercegowina": "ba",
  "Brazylia": "br",
  "Chorwacja": "hr",
  "Curacao": "cw",
  "Curaçao": "cw",
  "Czechy": "cz",
  "DR Konga": "cd",
  "Egipt": "eg",
  "Ekwador": "ec",
  "Francja": "fr",
  "Ghana": "gh",
  "Haiti": "ht",
  "Hiszpania": "es",
  "Holandia": "nl",
  "Irak": "iq",
  "Iran": "ir",
  "Japonia": "jp",
  "Jordania": "jo",
  "Kanada": "ca",
  "Katar": "qa",
  "Kolumbia": "co",
  "Korea Południowa": "kr",
  "Maroko": "ma",
  "Meksyk": "mx",
  "Niemcy": "de",
  "Norwegia": "no",
  "Nowa Zelandia": "nz",
  "Panama": "pa",
  "Paragwaj": "py",
  "Polska": "pl",
  "Portugalia": "pt",
  "Republika Południowej Afryki": "za",
  "Republika Zielonego Przylądka": "cv",
  "Senegal": "sn",
  "Szkocja": "gb-sct",
  "Szwajcaria": "ch",
  "Szwecja": "se",
  "Tunezja": "tn",
  "Turcja": "tr",
  "USA": "us",
  "Urugwaj": "uy",
  "Uzbekistan": "uz",
  "Wybrzeże Kości Słoniowej": "ci",
};

export function getFlagUrl(team: string): string | null {
  const code = countryCodes[team];
  if (!code) return null;
  return `https://hatscripts.github.io/circle-flags/flags/${code}.svg`;
}
